name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Install dependencies for all projects
      run: dotnet restore
      
    - name: Build all projects
      run: dotnet build --configuration Release --no-restore

    - name: Publish portal project in Release mode
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: drop
        path:  ${{ github.workspace }}/taa-portal/
        if-no-files-found: error
        
    - name: Upload a Build Artifact for bicep
      uses: actions/upload-artifact@v2.1.3
      with:
        name: bicep-template
        path: deploy.bicep
        if-no-files-found: error

  relase-to-dev:
    runs-on: ubuntu-latest
    needs: build 
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: drop
        path: ./taa-portal/

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: pethouse
        publish-profile: ${{ secrets.PET_HOUSE_PUBLISH_PROFILE }}
        package: ./taa-portal/

    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SP_PET_HOUSE }}
        
    - name: Azure Key Vault Action
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "kv-pethouse"
        secrets: 'GlobalPassword, SimulatedFailureChance'
      id: myGetSecretAction
        
    - name: 'Azure app setting update'        
      uses: azure/appservice-settings@v1
      with:
        app-name: 'pethouse'
        app-settings-json: |
          [
            {
              "name": "GlobalPassword",
              "value": " ${{ steps.myGetSecretAction.outputs.GlobalPassword }}",
              "slotSetting": false
            },
            {
              "name": "SimulatedFailureChance",
              "value": "${{ steps.myGetSecretAction.outputs.SimulatedFailureChance  }}",
              "slotSetting": false
            }
          ]
          
  relase-to-prod:
    runs-on: ubuntu-latest
    needs: relase-to-dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      PROD_APP_SERVICE_PLAN_NAME: pet_house_app_service_prod
      PROD_KEY_VAULT_NAME: kv-pethouse-prod
      PROD_WEB_APP_NAME: pethouse_prod
    steps:
    - name: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: bicep-template
        path: ./bicep-template/

    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SP_PET_HOUSE_PROD }}
        
    - name: bicep template deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./bicep-template/deploy.bicep
        parameters: tenantGuid=${{ secrets.AG_TENANT_GUID }} appServicePlanName=${{ env.PROD_APP_SERVICE_PLAN_NAME }} keyVaultName=${{ env.PROD_KEY_VAULT_NAME }} webAppName=${{ env.PROD_WEB_APP_NAME }} resourceGroupServicePrincipalManagedApplicationObjectId=${{ secrets.GHA_MSAG_RG_PROD_AUEAST_AZSPRINTSERIES_SP_MANAGED_APP_OBJECT_ID }}
        
    - name: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: drop
        path: ./taa-portal/
        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: pethouse
        publish-profile: ${{ secrets.PET_HOUSE_PUBLISH_PROFILE }}
        package: ./taa-portal/
        
    - name: Azure Key Vault Action
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "kv-pethouse"
        secrets: 'GlobalPassword, SimulatedFailureChance'
      id: myGetSecretAction
        
    - name: 'Azure app setting update'        
      uses: azure/appservice-settings@v1
      with:
        app-name: 'pethouse'
        app-settings-json: |
          [
            {
              "name": "GlobalPassword",
              "value": " ${{ steps.myGetSecretAction.outputs.GlobalPassword }}",
              "slotSetting": false
            },
            {
              "name": "SimulatedFailureChance",
              "value": "${{ steps.myGetSecretAction.outputs.SimulatedFailureChance  }}",
              "slotSetting": false
            }
          ]          
